### ISSUE TITLE
Connection not interrupting

### ISSUE THREAD

**Issue by auchri** [TakahikoKawasaki/nv-websocket-client#55]
I tried to use your WebSocket client in my android app.

But I found a issue: If I turn the internet on the device off, the connection seems to be still available and `onDisconnected` (or one of the other callbacks) is not called.

I'm using version 1.27

**Comment by TakahikoKawasaki** [comment]
Thank you very much. I have to find a way to solve this issue.

**Comment by rdcw** [comment]
I also have this issue!

**Comment by TakahikoKawasaki** [comment]
After thinking over this, my current conclusion is that this issue should not (or cannot) be solved in nv-websocket-client library because the library does not receive any notification about the network disconnection from the underlying system (Android).

If I were you, I would implement a class that extends <code>**[BroadcastReceiver](https://developer.android.com/reference/android/content/BroadcastReceiver.html)**</code> and register it so that it can respond to connectivity change (<code>android.net.conn.CONNECTIVITY_CHANGE</code>). And in the implementation of <code>**[onReceive()](https://developer.android.com/reference/android/content/BroadcastReceiver.html#onReceive(android.content.Context,%20android.content.Intent))**</code> method, I would call <code>**WebSocket.[disconnect()](http://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocket.html#disconnect-int-java.lang.String-)**</code> method to close the WebSocket connection.

```java
@Override
public void onReceive(Context context, Intent intent)
{
    ConnectivityManager manager = (ConnectivityManager)
        context.getSystemService(Context.CONNECTIVITY_SERVICE);

    NetworkInfo info = manager.getActiveNetworkInfo();

    // If network is not available.
    if (info == null)
    {
        // Close the WebSocket connection.
        websocket.disconnect(
            WebSocketCloseCode.AWAY,
            "Network was lost on the client side.");
    }
}
```

**Comment by afarber** [comment]
Isn't this issue "auto"-detectable by using `ws.setPingInterval(60 * 1000);`?

**Comment by TakahikoKawasaki** [comment]
@afarber Yes. If ping frames are sent periodically, network disconnection will be eventually detected as an error.

**Comment by riodevista** [comment]
@TakahikoKawasaki 
Hello! Thank you for your awesome library.
Could you tell me please a good practise to reconnect websocket?
For example, user lost connection and method onDisconnected called.
Via `onDisconnected(...)` I call `webSocket = websocket.recreate().connect()`, but the Internet is still missing. Is there any way to trying to reconnect as long until you connected?

**Comment by TakahikoKawasaki** [comment]
@riodevista Sorry for this very late reply. You can find some hints in #91 .

It would be better to provide a reconnection example that works out-of-the-box, but it will be difficult for me to spare time to implement it.

**Comment by KavyrshinR** [comment]
@TakahikoKawasaki Hello!

I'm using your library v1.31
I create connection and set ping interval. When I'm turn server off, connection does not interrupting.

`ws = new WebSocketFactory().createSocket("ws://" + ip + ":80/", 4000);
 ws.setPingInterval(4000);
 ws.addListener(this);
 ws.connectAsynchronously();`

How to solve this problem?

**Comment by KavyrshinR** [comment]
The connection was interrupted after 6 minutes

**Comment by auchri** [comment]
I switched to the websockets from okhttp, since it's maintained and works better.

**Comment by Begemot34** [comment]
> @afarber Yes. If ping frames are sent periodically, network disconnection will be eventually detected as an error.

Im try it
`                    WebSocketFactory factory = new WebSocketFactory();
                    SSLContext context = NaiveSSLContext.getInstance("TLS");
                    factory.setSSLContext(context);
                    ws = factory.createSocket(host);
                    ws.addListener(new SocketListener());
                    ws.setPingInterval(30 * 1000);
                    ws.connect();
`
and off internet on device(fly mode) but onDisconnected not happen after 30sec
